In [8]:
import numpy as np
import time

In [40]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a.dtype

dtype('int64')

In [52]:
a = np.zeros([100,100],dtype=int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
a = np.ones([9,9],dtype=int)
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [58]:
a = np.linspace(2,100,10)
a

array([  2.        ,  12.88888889,  23.77777778,  34.66666667,
        45.55555556,  56.44444444,  67.33333333,  78.22222222,
        89.11111111, 100.        ])

In [59]:
a = np.arange(10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [69]:
a = np.sum([10,10])
a

np.int64(20)